name: Katalon Web Test

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  katalon-web-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Java (required for Katalon)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # Specify the JDK distribution

      # Download Katalon Studio version 9.7.2
      - name: Download Katalon Studio
        run: |
          wget https://download.katalon.com/9.7.2/Katalon_Studio_Engine_Linux_64-9.7.2.tar.gz -O katalon.tar.gz
          tar -xzf katalon.tar.gz -C /opt/
          # Set the KATALON_HOME path based on the extracted version
          export KATALON_HOME=/opt/Katalon_Studio_Engine_Linux_64-9.7.2
          echo "Katalon Studio downloaded and extracted."

      # Verify Katalon installation
      - name: Verify Katalon Installation
        run: |
          ls $KATALON_HOME  # List files in the Katalon directory to check extraction
          echo $KATALON_HOME/katalonc  # Print the path to the Katalon executable

      # Run Katalon Studio tests
      - name: Run Katalon tests
        run: |
          $KATALON_HOME/katalonc \
          -noSplash \
          -runMode=console \
          -projectPath=$(pwd)/TESTJIRA.prj \
          -retry=0 \
          -testSuitePath="Test Suites/status.ts" \
          -browserType="Chrome" \
          -apiKey=$KATALON_API_KEY
        env:
          KATALON_API_KEY: ${{ secrets.KATALON_API_KEY }}

      # Upload test results as artifacts (optional)
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: $(pwd)/Reports  # Adjust based on your project structure
